{
 "title": "Voting Application",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Average CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(wmi_cpu_time_total{mode=\"idle\"}[2m])) * 100) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IIS average number of requests per second in last 5m",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum((rate(win_aspnet_app_Requests_Total[5m]))) by (app_kubernetes_io_instance)"
    }
   ]
  },
  {
   "title": "Heatmap for duration of getting survery results",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(votingapplication_getsurveyresult_duration_seconds_bucket[2m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Number of votes added to the database in the last 5m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(votingapplication_db_added_votes[5m])) by (app_kubernetes_io_instance) * 300",
     "legendFormat": "Votes in the last 5 minutes"
    }
   ]
  }
 ]
}